### PR TITLE
Add missing input.name parameter for evaluation of config.name

### PR DESCRIPTION
**Pull request by KowalskiTom**
Add missing input.name parameter for evaluation of config.name

### CODE REVIEW

**Comment by laardee** [comment]
@KowalskiTom should the role be named with the same name than the lambda? After your role [PR](https://github.com/serverless-components/aws-iam-role/pull/4) is merged, [this](https://github.com/serverless-components/aws-lambda/blob/master/serverless.js#L71-L77) could contain also a role name. 

Otherwise seems to work as expected.

**Comment by KowalskiTom** [comment]
@laardee good call. I have added this in.

**Comment by Podders** [comment]
@eahefnawy any plans to merge this one? It's kind of a needed option in my humble opinion

**Comment by nathanmargaglio** [comment]
What's stopping this from being merged?  I'd be willing to help get this thing up ASAP

**Comment by SarKurd** [comment]
@eahefnawy we desperately need this, could you please review?

**Comment by Belco90** [comment]
Another one here needing this ✋

**Comment by JStein92** [comment]
@eahefnawy we need this as well.

**Comment by watanabeyu** [comment]
@eahefnawy please merge

**Comment by falecci-morean** [comment]
Need this as well :)

**Comment by eahefnawy** [comment]
Thanks all! We rebuilt the entire thing from scratch and updated it for Components V2 and incorporated this change.

**Comment by andidev** [comment]
@eahefnawy 
When is this released?

**Comment by eahefnawy** [comment]
It's already out. Check out the readme:
https://github.com/serverless-components/aws-lambda/

**Pull request closed without merging**
