### PR TITLE
add logs and metrics methods

### PR DESCRIPTION
**Pull request by austencollins**
This is a first pass at adding experimental logs and metrics methods.

One of the goals is to have standard inputs and outputs across `logs()` and `metrics()` methods across all components.  Here is an attempt at that.

### CODE REVIEW

**Comment by eahefnawy** [comment]
@ac360 so this implementation doesn't actually console.log the logs. Is it meant to be used only programmatically and not via the CLI?

**Comment by austencollins** [comment]
Sorry, bad PR description.  The answer is yes and no.

As always, it's up to the context to handle the outputs.  In order to make it easier for contexts (cli, gui) to handle outputs, I've created a standard format for the outputs of both `logs()` and `metrics()` so that contexts can handle those outputs **the same way across all components**.

`logs()` returns an array with standard properties `timestamp`, `message`.  And an object called `meta` for custom properties.  Ideally, all components can use the same simple format for their `logs()` methods, since the format is very general.  This enables the CLI/Template Component to define a common experience for all `logs()` methods, like a nice printed list of logs in the terminal.

```javascript
{
  logs: [
    {
       timestamp: '2019-09-22T22:21:30.645Z',
       message: '1',
       meta: { requestId: '1981230981j1' }
    }
  ]
}
```

`metrics()` also returns an array with standard properties `type`, `name`, `keys`, `values`.  Ideally, all components can use the same simple format for their `metrics()` methods, since the format is very general.  This enables the CLI/Template Component to define a common experience for all `metrics()` methods.  In this case, the values returned are meant to populate charts.

```javascript
{
  metrics: [
    {
       type: 'keyVal', // A list of keys and values meant to populate line/bar charts
       name: 'Invocations', // The metric name
       keys: [
         '2019-09-22T22:21:30.645Z'
       ],
       values: [
         6
       ]
    }
  ]
}
```

**Comment by eahefnawy** [comment]
I like the idea of Context controlling logging. This is related to an issue @laardee opened here:
https://github.com/serverless/components/issues/494

**Comment by skierkowski** [comment]
Closing since I assume this is no longer relevant.

**Pull request closed without merging**
